name: Repo Keep Alive

on:
  schedule:
    # 每月 1 号运行
    # - cron: '0 0 1 * *'
    # 每天 UTC 18:00 触发，即北京时间次日凌晨 02:00
    - cron: '0 18 * * *'
  workflow_dispatch: 

jobs:
  active-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Keepalive Branch
        uses: actions/checkout@v4
        with:
          ref: keepalive # 确保操作的是 keepalive 分支

      - name: Update Heartbeat File
        run: |
          # 设置用户信息
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 追加当前时间到文件（如果文件不存在会自动创建）
          echo "Last heartbeat: $(date)" >> KEEP_ALIVE.md
          
          # 提交并推送
          git add KEEP_ALIVE.md
          git commit -m "Chore: Update heartbeat $(date +'%Y-%m-%d')"
          git push origin keepalive
